### ISSUE TITLE
An error occurred:

### ISSUE THREAD

**Issue by linjian-ufo** [kijai/ComfyUI-DeepSeek-VL#1]
AttributeError: module 'wandb.proto.wandb_internal_pb2' has no attribute 'Result'

**Comment by kijai** [comment]
Full error? wandb isn't used, I don't even have it installed myself currently. Could be protobuff version, though it wasn't in any requirements. Or most likely it's about transformers version, I'll add the minimum to requirements.

**Comment by linjian-ufo** [comment]
> 完全错误？没有使用 wandb，我什至没有自己安装它。可能是 protobuff 版本，尽管它没有任何要求。或者很可能是关于变形金刚版本，我会在要求中添加最低要求。

Thank you for your answer, I will try these two versions first, thank you very much!

**Comment by linjian-ufo** [comment]
Traceback (most recent call last):
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\ComfyUI\custom_nodes\ComfyUI-DeepSeek-VL\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\ComfyUI\custom_nodes\ComfyUI-DeepSeek-VL\nodes.py", line 6, in <module>
    from .deepseek_vl.models import VLChatProcessor, MultiModalityCausalLM
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\ComfyUI\custom_nodes\ComfyUI-DeepSeek-VL\deepseek_vl\models\__init__.py", line 21, in <module>
    from .modeling_vlm import MultiModalityCausalLM
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\ComfyUI\custom_nodes\ComfyUI-DeepSeek-VL\deepseek_vl\models\modeling_vlm.py", line 32, in <module>
    from .clip_encoder import CLIPVisionTower, HybridVisionTower
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\ComfyUI\custom_nodes\ComfyUI-DeepSeek-VL\deepseek_vl\models\clip_encoder.py", line 28, in <module>
    from .siglip_vit import create_siglip_vit
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\ComfyUI\custom_nodes\ComfyUI-DeepSeek-VL\deepseek_vl\models\siglip_vit.py", line 42, in <module>
    from timm.layers import (
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\timm\__init__.py", line 3, in <module>
    from .models import create_model, list_models, list_pretrained, is_model, list_modules, model_entrypoint, \
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\timm\models\__init__.py", line 1, in <module>
    from .beit import *
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\timm\models\beit.py", line 49, in <module>
    from timm.data import IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\timm\data\__init__.py", line 5, in <module>
    from .dataset import ImageDataset, IterableImageDataset, AugMixDataset
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\timm\data\dataset.py", line 13, in <module>
    from .readers import create_reader
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\timm\data\readers\__init__.py", line 1, in <module>
    from .reader_factory import create_reader
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\timm\data\readers\reader_factory.py", line 4, in <module>
    from .reader_image_folder import ReaderImageFolder
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\timm\data\readers\reader_image_folder.py", line 11, in <module>
    from timm.utils.misc import natural_key
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\timm\utils\__init__.py", line 15, in <module>
    from .summary import update_summary, get_outdir
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\timm\utils\summary.py", line 9, in <module>
    import wandb
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\wandb\__init__.py", line 27, in <module>
    from wandb import sdk as wandb_sdk
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\wandb\sdk\__init__.py", line 25, in <module>
    from .artifacts.artifact import Artifact
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\wandb\sdk\artifacts\artifact.py", line 46, in <module>
    from wandb.apis.normalize import normalize_exceptions
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\wandb\apis\__init__.py", line 43, in <module>
    from .internal import Api as InternalApi  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\wandb\apis\internal.py", line 3, in <module>
    from wandb.sdk.internal.internal_api import Api as InternalApi
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 48, in <module>
    from ..lib import retry
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\wandb\sdk\lib\retry.py", line 17, in <module>
    from .mailbox import ContextCancelledError
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 102, in <module>
    class _MailboxSlot:
  File "D:\ComfyUI_windows_pytorch2.2.0_nvidia_cuda121_xformers0.0.23or_cpu\python_embeded\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 103, in _MailboxSlot
    _result: Optional[pb.Result]
                      ^^^^^^^^^
AttributeError: module 'wandb.proto.wandb_internal_pb2' has no attribute 'Result'

**Comment by lcsmamo** [comment]
启动命令提示符

输入命令进入custom_nodes目录（插件目录）:
cd custom_nodes

输入命令下载插件：
git clone https://github.com/kijai/ComfyUI-DeepSeek-VL

输入命令安装插件管理器的依赖
python -m pip install -r ComfyUI-DeepSeek-VL/requirements.txt
