### ISSUE TITLE
加载完模型后报错：Input type (struct c10::BFloat16) and bias type (float) should be the same

### ISSUE THREAD

**Issue by Leonard-Li777** [kijai/ComfyUI-DeepSeek-VL#2]
!!! Exception during processing!!! Input type (struct c10::BFloat16) and bias type (float) should be the same
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1-2\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI-aki-v1-2\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI-aki-v1-2\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI-aki-v1-2\custom_nodes\ComfyUI-DeepSeek-VL\nodes.py", line 144, in process
    inputs_embeds = model.prepare_inputs_embeds(**prepare_inputs)
  File "E:\ComfyUI-aki-v1-2\custom_nodes\ComfyUI-DeepSeek-VL\deepseek_vl\models\modeling_vlm.py", line 150, in prepare_inputs_embeds
    images_embeds = self.aligner(self.vision_model(images))
  File "E:\ComfyUI-aki-v1-2\python\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ComfyUI-aki-v1-2\python\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ComfyUI-aki-v1-2\custom_nodes\ComfyUI-DeepSeek-VL\deepseek_vl\models\clip_encoder.py", line 183, in forward
    high_res = self.vision_tower_high(high_images)
  File "E:\ComfyUI-aki-v1-2\python\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ComfyUI-aki-v1-2\python\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ComfyUI-aki-v1-2\custom_nodes\ComfyUI-DeepSeek-VL\deepseek_vl\models\sam.py", line 502, in forward
    x = self.proj(x)
  File "E:\ComfyUI-aki-v1-2\python\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ComfyUI-aki-v1-2\python\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ComfyUI-aki-v1-2\python\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "E:\ComfyUI-aki-v1-2\python\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (struct c10::BFloat16) and bias type (float) should be the same

comfyui 已经更新到最新了版

**Comment by MaraScott** [comment]
Hi @kijai , any chance to get some insight from you ?

I got that issue too `RuntimeError: Input type (struct c10::BFloat16) and bias type (float) should be the same` with p312 base
